# style-data.py — master design data for all art styles (palette, best-for, key css technique)
# Used by add-design.py (design.md generator) and regen-index.py (swatches)

DESIGN = {
    'acid': ['#ff2d78', '#ffd500', '#00f0ff'],
    'aero_frutiger': ['#7ec8e3', '#4aa3c9', '#ffffff'],
    'art_deco': ['#d4af37', '#101010', '#f2ead3'],
    'art_nouveau': ['#a8863d', '#2f3a2f', '#f5efe4'],
    'barbiecore': ['#ff2d78', '#ffd9e8', '#ffffff'],
    'bauhaus': ['#e02a25', '#2a2a2a', '#f5f0e0'],
    'bento_ui': ['#6366f1', '#22c55e', '#f3f4f6'],
    'biopunk': ['#00ff85', '#0a1f14', '#1b5e3a'],
    'brutalism': ['#ffffff', '#000000', '#3b82f6'],
    'candy_pop': ['#ff8fab', '#ffd1dc', '#fff0f3'],
    'claymorphism': ['#d4a373', '#fae1dd', '#f8edeb'],
    'constructivism': ['#e31b23', '#000000', '#f2f2f2'],
    'corporate_memphis': ['#ff8a65', '#4fc3f7', '#ffd54f'],
    'cottagecore': ['#c49a6c', '#8aa87e', '#f5ead9'],
    'cyberpunk': ['#00fff9', '#ff00ff', '#0a0a12'],
    'dada': ['#ff004c', '#ffd500', '#000000'],
    'dark_academia': ['#8a6a4a', '#d4b483', '#2b2118'],
    'dark_minimal': ['#7c8cff', '#e8e8ea', '#0a0a0b'],
    'de_stijl': ['#e02a25', '#2a2a2a', '#f5f0e0'],
    'editorial': ['#b08d3e', '#1a1a1a', '#faf9f7'],
    'fairycore': ['#c084fc', '#f472b6', '#ede9fe'],
    'flat_design': ['#0984e3', '#00b894', '#ffeaa7'],
    'glassmorphism': ['#667eea', '#764ba2', '#f093fb'],
    'gothic': ['#c9a227', '#3a2a1a', '#1a1410'],
    'grandmacore': ['#b07040', '#8a5a3a', '#faf3e8'],
    'grunge': ['#8a5a3a', '#c9a227', '#2a2a2a'],
    'holographic': ['#ff2d95', '#8b5cf6', '#06b6d4'],
    'isometric': ['#6366f1', '#22c55e', '#f59e0b'],
    'japandi': ['#8a7a5a', '#7a6c4c', '#e5ddcf'],
    'liminal_space': ['#9aa0a8', '#e8e6e3', '#1a1a1a'],
    'manga': ['#ff004c', '#ffffff', '#1a1a1a'],
    'material_design': ['#6200ee', '#ffd54f', '#4dd0e1'],
    'maximalism': ['#ff2d78', '#ffd500', '#00f0ff'],
    'medieval': ['#c9a227', '#8a6a3a', '#3a2a1a'],
    'memphis': ['#ff5a5f', '#00d2d3', '#feca57'],
    'minimal_horror': ['#0a0a0a', '#2a2a2a', '#e8e8e8'],
    'minimalistic_futuristic': ['#0f172a', '#38bdf8', '#e2e8f0'],
    'mystical_forest': ['#1b4332', '#52b788', '#ffd60a'],
    'neo_brutalism': ['#ffde59', '#ff5c8a', '#38d9a9'],
    'neumorphism': ['#e0e5ec', '#a3b1c6', '#ffffff'],
    'noir': ['#0d0d0d', '#2a2a2a', '#f0ece4'],
    'oceanic': ['#0a4d68', '#48cae4', '#90e0ef'],
    'old_web': ['#00ff00', '#000080', '#ffff00'],
    'pixelated': ['#1a1a2e', '#ffd500', '#00ff85'],
    'pop_art': ['#ff004c', '#00d2d3', '#ffd500'],
    'psychedelic': ['#ff2d78', '#8b5cf6', '#00f0ff'],
    'retro_futurism': ['#c53d2f', '#f2c94c', '#3a7a6a'],
    'rococo': ['#d4af37', '#f5f0e0', '#a87a5a'],
    'saccharine': ['#ff9ecb', '#fbd3e9', '#b388eb'],
    'scandinavian': ['#2f2f2f', '#8a7a4f', '#f7f5f0'],
    'skeuomorphism': ['#6b4226', '#7a4a2b', '#ffd479'],
    'slasher': ['#b00020', '#1a1a1a', '#e8e8e8'],
    'solarpunk': ['#15803d', '#84cc16', '#f0fdf4'],
    'steampunk': ['#8a6a35', '#ffd97a', '#2a2118'],
    'surreal': ['#8b5cf6', '#ff2d78', '#00f0ff'],
    'swiss_style': ['#e02a25', '#2a2a2a', '#f5f0e0'],
    'techno_baroque': ['#d4af37', '#8b5cf6', '#1a1030'],
    'terminal': ['#00ff41', '#0a0a0a', '#39ff14'],
    'typodriven': ['#1a1a1a', '#e02a25', '#f5f0e0'],
    'ukiyo_e': ['#2f5d50', '#c9a227', '#f5f0e0'],
    'vaporwave': ['#ff2d78', '#8b5cf6', '#00f0ff'],
    'vhs_glitch': ['#00ff9f', '#ff004c', '#0a0a0a'],
    'web20': ['#2a82f5', '#ffcc00', '#ffffff'],
    'western': ['#8a5a2a', '#c9a227', '#f5e6d3'],
    'y2k': ['#ff2d78', '#00f0ff', '#d4af37'],
}

BEST = {
    'acid': 'Brand kreatif, musik, NFT/web3, event visual',
    'aero_frutiger': 'Produk teknologi, portal, iklan digital era 2000-an',
    'art_deco': 'Brand premium, hotel luxury, fashion, wedding',
    'art_nouveau': 'Brand organik, spa, kecantikan, editorial',
    'barbiecore': 'Fashion, kecantikan, brand wanita muda',
    'bauhaus': 'Arsitektur, seni, brand minimal geometris',
    'bento_ui': 'Dashboard SaaS, portfolio, landing page modern',
    'biopunk': 'Biotech, game sci-fi, brand futuristik organik',
    'brutalism': 'Brand eksperimental, portfolio edgy, seni digital',
    'candy_pop': 'Candy brand, game anak, brand fun',
    'claymorphism': 'SaaS, aplikasi mobile, dashboard modern',
    'constructivism': 'Poster, brand avant-garde, konten politik',
    'corporate_memphis': 'Startup, ilustrasi brand, blog friendly',
    'cottagecore': 'Brand lifestyle, kebun, handmade, bakery',
    'cyberpunk': 'Gaming, tech event, brand futuristik',
    'dada': 'Seni, brand absurd, karya eksperimental',
    'dark_academia': 'Brand literasi, kopi, perpustakaan, podcast',
    'dark_minimal': 'Portfolio, studio desain, brand premium',
    'de_stijl': 'Arsitektur, seni abstrak, brand minimal',
    'editorial': 'Majalah, media, brand literasi',
    'fairycore': 'Brand dongeng, skincare, wedding',
    'flat_design': 'SaaS, aplikasi, landing page modern',
    'glassmorphism': 'Dashboard, app premium, brand modern',
    'gothic': 'Hotel tua, brand gothic, event horror',
    'grandmacore': 'Brand vintage, handmade, bakery, teh',
    'grunge': 'Band musik, brand edgy, clothing',
    'holographic': 'Brand futuristik, kosmetik, tech',
    'isometric': 'Game, ilustrasi, brand tech',
    'japandi': 'Furniture, spa, brand slow-living',
    'liminal_space': 'Horror indie, seni, karya eksperimental',
    'manga': 'Game anime, brand Jepang, komik',
    'material_design': 'App Android, dashboard, produk Google',
    'maximalism': 'Brand ekspresif, fashion, seni',
    'medieval': 'Brand sejarah, game fantasy, festival',
    'memphis': 'Brand playful, retro 80-an, seni',
    'minimal_horror': 'Film horror, brand minimal seram',
    'minimalistic_futuristic': 'Tech startup, AI, produk futuristik',
    'mystical_forest': 'Game fantasy, spa alam, brand fantasi',
    'neo_brutalism': 'Startup bold, portfolio edgy, brand muda',
    'neumorphism': 'Dashboard, app, soft UI modern',
    'noir': 'Film, brand misteri, tema detektif',
    'oceanic': 'Brand laut, travel, spa',
    'old_web': 'Nostalgia, retro blog, karya eksperimental',
    'pixelated': 'Game retro, pixel art, brand 8-bit',
    'pop_art': 'Brand playful, seni populer, konsumer',
    'psychedelic': 'Festival, brand psikedelik, seni',
    'retro_futurism': 'Diner retro, brand travel, vintage',
    'rococo': 'Wedding, hotel luxury, brand mewah',
    'saccharine': 'Dessert, wedding, brand manis',
    'scandinavian': 'Furniture, interior, brand minimal',
    'skeuomorphism': 'Brand classic, dashboard vintage, nostalgia',
    'slasher': 'Horror, film, event bertema',
    'solarpunk': 'Brand eco, renewable energy, komunitas',
    'steampunk': 'Brand vintage-tech, event, escape room',
    'surreal': 'Seni, brand kreatif, karya eksperimental',
    'swiss_style': 'Brand design, arsitektur, media',
    'techno_baroque': 'Luxury-tech, NFT, avant-garde',
    'terminal': 'Brand dev, CLI tools, hacker',
    'typodriven': 'Editorial, fashion, brand tipografi',
    'ukiyo_e': 'Brand Jepang, seni, museum',
    'vaporwave': 'Brand retro, musik, nostalgia 80-an',
    'vhs_glitch': 'Brand analog, film, karya eksperimental',
    'web20': 'Brand nostalgia, social media, fun',
    'western': 'Restaurant western, brand outdoor, frontier',
    'y2k': 'Fashion, musik, brand futuristic-nostalgia',
}

CSS = {
    'acid': 'Gradien neon multi-warna + blur glow + bentuk cair animasi',
    'aero_frutiger': 'Gradien aqua transparan + highlight glossy',
    'art_deco': 'Sunburst pattern conic-gradient + border emas + serif dekoratif',
    'art_nouveau': 'Kurva whiplash SVG + motif flora + palet muted',
    'barbiecore': 'Palet hot pink bold + bentuk rounded + playful',
    'bauhaus': 'Bentuk geometris murni + warna primer + grid ketat',
    'bento_ui': 'Grid bento asimetris + kartu rounded + shadow halus',
    'biopunk': 'Neon hijau glow + tekstur biomassa + gradient organik',
    'brutalism': 'Raw HTML + border kasar + warna default + tanpa hiasan',
    'candy_pop': 'Pastel cerah + rounded besar + shadow lembut',
    'claymorphism': 'Box-shadow inset 3D + corner radius besar + tone clay',
    'constructivism': 'Diagonal tajam + merah-hitam + tipografi agresif',
    'corporate_memphis': 'Ilustrasi blobby flat + warna pastel cerah',
    'cottagecore': 'Motif bunga radial + border double vintage + krem hangat',
    'cyberpunk': 'Neon glow text-shadow + glitch RGB split + grid perspektif 3D',
    'dada': 'Kolase chaos + tipografi rusak + warna acak',
    'dark_academia': 'Serif antik + parchment texture + ornamen + sepia',
    'dark_minimal': 'Near-black canvas + satu warna aksen + tipografi ringan',
    'de_stijl': 'Grid + kotak warna primer + garis tebal horizontal-vertikal',
    'editorial': 'Grid majalah ketat + headline serif besar + whitespace',
    'fairycore': 'Sparkle melayang + pastel lavender-pink + glassmorphism lembut',
    'flat_design': 'Warna solid tanpa gradien + bentuk sederhana + tanpa shadow',
    'glassmorphism': 'Backdrop-filter blur + border semi-transparent + layering',
    'gothic': 'Lengkung lancip + emas + tekstur batu gelap',
    'grandmacore': 'Doily renda SVG + wallpaper bunga + border double',
    'grunge': 'Tekstur noise + font tangan + palet gelap vintage',
    'holographic': 'Gradien iridescent animasi + shimmer background-position',
    'isometric': 'Ilustrasi 3D axonometric + grid isometric + shadow',
    'japandi': 'Wabi-sabi + kayu hangat + warna tanah + ruang negatif',
    'liminal_space': 'Fluorescent pale + koridor kosong + uncanny minimal',
    'manga': 'Panel komik + speedline + tipografi bold + screentone',
    'material_design': 'Elevation shadow berlapis + kartu + warna primary bold',
    'maximalism': 'Layer bertumpuk + warna penuh + tekstur berlebihan',
    'medieval': 'Huruf Gothic + parchment + warna tanah dan emas',
    'memphis': 'Pola geometris berulang + warna neon 80-an + abstrak',
    'minimal_horror': 'Gelap + whitespace kosong + tipografi seram tipis',
    'minimalistic_futuristic': 'Gradien gelap + garis neon tipis + ruang luas',
    'mystical_forest': 'Hijau tua + glow firefly + tekstur daun',
    'neo_brutalism': 'Border hitam tebal + hard shadow tanpa blur + warna teriak',
    'neumorphism': 'Box-shadow ganda inset/outset + tone senada',
    'noir': 'High contrast hitam-putih + venetian blind overlay + serif',
    'oceanic': 'Gradien biru laut + tekstur air + elemen organik',
    'old_web': 'Marquee + tabel + background GIF + warna mencolok',
    'pixelated': 'Font bitmap + grid pixel + palet terbatas',
    'pop_art': 'Ben-Day dots + warna neon + konten mass culture',
    'psychedelic': 'Gradien pelangi + bentuk cair + warna acid',
    'retro_futurism': 'Starburst conic-gradient + roket CSS + orbit dashed',
    'rococo': 'Ornamen emas + lengkungan organik + pastel kaya',
    'saccharine': 'Pastel pink-ungu + dekorasi ribet + nuansa dongeng',
    'scandinavian': 'Hygge + kayu terang + ruang lapang + natural',
    'skeuomorphism': 'Tekstur kulit jahitan + tombol 3D + highlight glossy',
    'slasher': 'Darah merah + font serif tebal + tekstur goresan',
    'solarpunk': 'Hijau cerah + panel surya + bentuk organik + optimistis',
    'steampunk': 'Gear SVG berputar + kuningan + rivet + gauge',
    'surreal': 'Objek tidak masuk akal + gradien aneh + komposisi membingungkan',
    'swiss_style': 'Grid-based + Helvetica + hierarki ketat + minimal',
    'techno_baroque': 'Ornamen Baroque + elemen digital + emas-ungu',
    'terminal': 'Monospace hijau + cursor berkedip + teks ASCII',
    'typodriven': 'Tipografi raksasa + layout grid + hierarki huruf',
    'ukiyo_e': 'Garis outline tegas + gradien flat + warna earthy',
    'vaporwave': 'Gradien pink-ungu + kolom Romawi + glitch',
    'vhs_glitch': 'Scanline + chromatic aberration RGB + noise overlay',
    'web20': 'Tombol glossy + rounded corner + refleksi kaca + gradien biru',
    'western': 'Tekstur kayu + slab serif + palet frontier cokelat',
    'y2k': 'Gradien metallic + chrome + bentuk membulat + kilauan',
}
